### ISSUE TITLE
Méthode approchée pour le problème de décision (H)

### ISSUE THREAD

**Issue by arnaud-m** [Allez100dreau/merch-time#3]

**Comment by arnaud-m** [comment]
- La liste `items` ne sert à rien
- Préalloue `chosenItems`. Tu peux remarquer qu'initialiser un tableau est plus simple/court.
- Tester que le sac est plein seulement APRÈS avoir ajouté un objet.
- La fonction `isFeasible` n'est pas implémentée.

**Comment by Ossama98** [comment]
Participation : Ossama et Kevin

**Comment by arnaud-m** [comment]
En fait, on a besoin de vérifier si la capacité est atteinte quand on vient d'ajouter un objet dans le sac. 
Le bloc `if` peut donc être déplacé pour rendre le code plus efficace. 

Par ailleurs, l'algorithme ne renvoie pas toujours une solution remplissant exactement le sac-à-dos et ne respecte donc pas la spécification. 

https://github.com/Allez100dreau/merch-time/blob/2e80b1a13243545b0dd821141783353f088eab2d/src/main/java/unice/solver/SolverH.java#L27-L33

Ensuite, je suis étonné que ce code ne soit pas factorisé avec les autres solveurs. 

https://github.com/Allez100dreau/merch-time/blob/2e80b1a13243545b0dd821141783353f088eab2d/src/main/java/unice/solver/SolverH.java#L60-L68

Cette partie serait inutile si la méthode `solve`respectait la spécification. 

https://github.com/Allez100dreau/merch-time/blob/2e80b1a13243545b0dd821141783353f088eab2d/src/main/java/unice/solver/SolverH.java#L69-L76

**Comment by arnaud-m** [comment]
Bien. Le code est plus simple maintenant, non ?
