### ISSUE TITLE
Méthode exacte pour le problème d’énumération (E)

### ISSUE THREAD

**Issue by arnaud-m** [Allez100dreau/merch-time#5]

**Comment by iBananos** [comment]
Jérémy & Ralph : Réalisation du SolverE et des classes : lnstanceMT, SolutionMT, et MetaMerch.
Yasmine : Tests de la classe SolverE, JavaDoc générale du code, détections de bug & refactorisation du code.

**Comment by arnaud-m** [comment]
L'espace occupée par la solution partielle dans le sac-à-dos doit être calculé incrémentalement.
Cela permet un clacul en temps constant au lieu d'un calcul en temps linéaire. 

https://github.com/Allez100dreau/merch-time/blob/1951f8272fae21637cf303e1a1b24b5a8d99a0ef/src/main/java/unice/solver/SolverE.java#L89-L102

- Sans cesse ajouter et retirer des éléments dans une liste est inefficace.
- Vérifier qu'une solution avec des objets aux poids identiques est une bonne idée, mais l'implémentation est inefficace. 
- Par ailleurs, mémoriser la taille des objets plutôt que leurs positions vous oblige à reconstruire toutes les solutions dans `getIterator`
- Pour `isFeasible`, vous devez quand même résoudre le problème d'énumération et non celui de décision.

**Comment by arnaud-m** [comment]
Le code est beaucoup trop long. Essayez de simplifier ou au moins de définir des fonctions auxiliaires. 
à titre de comparaison, j'ai codé une méthode similaire à votre [generate-and-test](https://en.wikipedia.org/wiki/Trial_and_error) en R. Elle fait 15 lignes. 

Sinon, la méthode `getSolution`renvoie déjà une liste, non ? 
https://github.com/Allez100dreau/merch-time/blob/2e80b1a13243545b0dd821141783353f088eab2d/src/main/java/unice/solver/SolverE.java#L169-L182

**Comment by arnaud-m** [comment]
Bien commenté. Il y a encore quelques redondances et on pourrait probablement encore simplifier et raccourcir le code.
Mais, cela sera suffisant, car on doit quand même finir le projet. 

Pour l'exemple, voici un petit code d'énumération des solutions en R.
Il y a peut-être des idées à prendre pour simplifier, notamment la gestion des cas terminaux.,
```R
## Énumération des solutions remplissant exactement le sac-à-dos.
## EnumSSP(1:10, 25)
## Attention, on ne gère absolument pas les symétries
## EnumSSP(rep(1, 5), 3)
EnumSSP <- function(weights, capacity) {
    if(length(weights) == 0) {
        ## Il n'y a plus d'objets à ajouter
        if(capacity == 0) return(list(numeric(0)))
        else return(list())
    } else {
        weight <- weights[1]
        if(weight <= capacity) {
            ## Il reste de l'espace, on ajoute l'objet, puis on essaie de compléter la solution partielle
            sols <- EnumSSP(tail(weights, -1), capacity - weight)
            ## On ajoute l'objet courant aux solutions partielles renvoyées
            sols <- lapply(sols, function(x) append(x, weight))
        } else {
           ## On a dépassé la capacité du sac-à-dos
            sols <- list()
        }
        ## On renvoie les solutions avec l'objet courant, et celle sans l'objet courant.
        sols <- append(sols, EnumSSP(tail(weights, -1), capacity))
        return(sols)
    }
}
```
